
spring.application.name=SpendWise_app
server.port=8080
#conectando a una base de datos#

#1. Info general de la conexion#
spring.datasource.url=jdbc:h2:mem:spendwise_app_bd
spring.datasource.username=sa
spring.datasource.password=

#2. Habilitar la base de datos en memori h2#
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#3. Habilitar el JPA#
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=create